[package]
name = "reveal_answer"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.6.0", features = ["integer"] }
tfhe_engine = {path = "../tfhe_engine/", version = "0.1.0"}
serde_json = "1.0.115"
