[package]
name = "create_client"
version = "0.1.0"
edition = "2021"
authors = ["Anthony Eufemio <tymat@pris.im>"]
license = "BSD-3"

[dependencies]
tfhe = {path = "../tfhe/", version = "0.1.0"}
serde_json = "1.0.115"